### ISSUE TITLE
stupid plugin ive ever seen

### ISSUE THREAD

**Issue by cuzimrealy** [David-pm-pl/ChestKits#1]
Error: "Class "DavidGlitch04\ChestKits\libs\jojoe77777\FormAPI\SimpleForm" not found" (EXCEPTION) in "plugins/ChestKits (1).phar/src/Form/CKitsForm" at line 41
--- Stack trace ---
  #0 plugins/ChestKits (1).phar/src/Form/CKitsForm(33): DavidGlitch04\ChestKits\Form\CKitsForm->openForm(object pocketmine\player\Player#121739)
  #1 plugins/ChestKits (1).phar/src/Command/CKitsCommand(54): DavidGlitch04\ChestKits\Form\CKitsForm->__construct(object DavidGlitch04\ChestKits\ChestKits#25787, object pocketmine\player\Player#121739)
  #2 pmsrc/src/command/SimpleCommandMap(205): DavidGlitch04\ChestKits\Command\CKitsCommand->execute(object pocketmine\player\Player#121739, string[9] chestkits, array[0])
  #3 pmsrc/src/Server(1446): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#121739, string[9] chestkits)
  #4 pmsrc/src/player/Player(1410): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#121739, string[9] chestkits)
  #5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(737): pocketmine\player\Player->chat(string[10] /chestkits)
  #6 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(51): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#140746)
  #7 pmsrc/src/network/mcpe/NetworkSession(388): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#128226)
  #8 pmsrc/src/network/mcpe/NetworkSession(351): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#140746, string[31] M./chestkits..M..z..W.M..C.6...)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[35] ....O.H-...,)f..{..JnA.?..o._..g`..)
  #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[44] .............z.X.(.8...>..N.[.........WR..I.)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#28774)
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1655321437.666)
  #15 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #16 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[35] C:\Users\Auroz\Desktop\servers\Hub\, string[43] C:\Users\Auroz\Desktop\servers\Hub\plugins\)
  #17 pmsrc/src/PocketMine(327): pocketmine\server()
  #18 pmsrc(11): require(string[79] phar://C:/Users/Auroz/Desktop/servers/Hub/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[21:30:37.663] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[21:30:37.675] [Server thread/EMERGENCY]: Please upload the "C:/Users/Auroz/Desktop/servers/Hub/crashdumps/Wed_Jun_15-21.30.37-CAT_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[21:30:38.943] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/6991781 or use the ID #6991781.
[21:30:38.945] [Server thread/EMERGENCY]: Forcing server shutdown

WHATS POINT OF INSTALLING IT

**Comment by 0xliam627** [comment]
https://poggit.pmmp.io/p/ChestKits
