### ISSUE TITLE
error when running /chestkits

### ISSUE THREAD

**Issue by TheUtopianPlayz** [David-pm-pl/ChestKits#3]
PocketMine-MP Crash Dump Thu Jun 22 11:49:34 UTC 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.1.19
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: ChestKits

Error: Class "DavidGlitch04\ChestKits\DavidGlitch04\ChestKits\libs\Vecnavium\FormsUI\Form" not found
File: plugins/ChestKits.phar/src/libs/Vecnavium/FormsUI/SimpleForm
Line: 7
Type: Error
Backtrace:
#0 pmsrc/src/thread/ThreadSafeClassLoader(133): include()
#1 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[57] DavidGlitch04\ChestKits\libs\Vecnavium\FormsUI\SimpleForm)
#2 plugins/ChestKits.phar/src/Form/CKitsForm(43): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[57] DavidGlitch04\ChestKits\libs\Vecnavium\FormsUI\SimpleForm)
#3 plugins/ChestKits.phar/src/Form/CKitsForm(35): DavidGlitch04\ChestKits\Form\CKitsForm->openForm(object pocketmine\player\Player#168578)
#4 plugins/ChestKits.phar/src/Command/CKitsCommand(56): DavidGlitch04\ChestKits\Form\CKitsForm->__construct(object DavidGlitch04\ChestKits\ChestKits#40926, object pocketmine\player\Player#168578)
#5 pmsrc/src/command/SimpleCommandMap(212): DavidGlitch04\ChestKits\Command\CKitsCommand->execute(object pocketmine\player\Player#168578, string[9] chestkits, array[0])
#6 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#168578, string[9] chestkits)
#7 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#168578, string[9] chestkits)
#8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[10] /chestkits)
#9 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#109327)
#10 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#150340)
#11 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#109327, string[32] M./chestkits..@....Nt1.........D)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[81] S...O.H-...,)f.t..x.Y.......e.9...._.....L`d8.k?%o......B....u....A...L.......4.)
#13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[90] ...G)<h.....$.DN.I......,.x.....,.o..4..-R..d..-.4}.{...g.6ADE..e._L(.-...1..o..)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#184937)
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#16 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#18 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1687434575.0146)
#19 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#20 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[37] /portal2elysium/minecraft/kitpvplive/, string[45] /portal2elysium/minecraft/kitpvplive/plugins/)
#21 pmsrc/src/PocketMine(357): pocketmine\server()
#22 pmsrc(11): require(string[81] phar:///portal2elysium/minecraft/kitpvplive/PocketMine-MP.phar/src/PocketMine.ph)

Code:
[1] <?php
[2] 
[3] declare(strict_types = 1);
[4] 
[5] namespace DavidGlitch04\ChestKits\DavidGlitch04\ChestKits\libs\Vecnavium\FormsUI;
[6] 
[7] class SimpleForm extends Form {
[8] 
[9]     const IMAGE_TYPE_PATH = 0;
[10]     const IMAGE_TYPE_URL = 1;
[11] 
[12]     /** @var string */
[13]     private $content = "";
[14] 
[15]     private $labelMap = [];
[16] 
[17]     /**

Loaded plugins:
BedrockEconomy 2.1.1 by cooldogedev for API(s) 5.0.0
BetterMute 1.1.4 by supercrafter333 for API(s) 5.0.0
BuilderTools 2.0.0-beta1 by CzechPMDevs, VixikHD, dadodasyra for API(s) 5.0.0
ChestKits 0.0.2 by  for API(s) 5.0.0
ChestShop 5.3.7 by  for API(s) 5.0.0
DevTools 1.17.0 by PocketMine Team for API(s) 5.0.0
FormAPI 2.1.1 by jojoe77777 for API(s) 4.0.0, 5.0.0
HumanNPC 0.0.3 by BeeAZ for API(s) 5.0.0
InvSee 2.3.1 by BlockHorizons for API(s) 5.0.0
MOTDShuffle 1.4.0 by HBIDamian for API(s) 5.0.0
MultiWorld 2.1.0-beta2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 5.0.0
VanishV2 4.0.2 by sqrrl for API(s) 5.0.0

uname -a: Linux p2e 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64
Zend version: 4.1.19
Composer libraries: 
- adhocore/json-comment 1.2.1@651023f9fe52e9efa2198cbaf6e481d1968e2377
- brick/math 0.11.0@0ad82ce168c82ba30d1c01ec86116ab52f589478
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.5.0@42060ed45344789fb9f21f9f1864fc47b9e3507b
- netresearch/jsonmapper unknown@unknown
- pocketmine/bedrock-block-upgrade-schema 2.2.0@79bb3ad542ef19e828fdf1fa6adc54f1fa4b3bb5
- pocketmine/bedrock-data 2.3.0+bedrock-1.20.0@b3dd3f4b8e3b6759c5d84de6ec85bb20b668c3a9
- pocketmine/bedrock-item-upgrade-schema 1.3.0@b16c59cfae08833f180dd82f88de7c1f43bc67c9
- pocketmine/bedrock-protocol 22.0.0+bedrock-1.20.0@ceff28a0bd5d248f37fb97be3e836d536e37526e
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/color 0.3.1@a0421f1e9e0b0c619300fb92d593283378f6a5e1
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.19.5@71af5f9bd23b4e4bad8920dac7f4fe08e5205f7d
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/math 0.4.3@47a243d320b01c8099d65309967934c188111549
- pocketmine/nbt 0.3.4@62c02464c6708b2467c1e1a2af01af09d5114eda
- pocketmine/netresearch-jsonmapper v4.2.999@f700806dec756ed825a8200dc2950ead98265956
- pocketmine/pocketmine-mp 5.1.2@7cd317bf398a017f7c690a475c5a67650c610323
- pocketmine/raklib 0.15.1@79b7b4d1d7516dc6e322514453645ad9452b20ca
- pocketmine/raklib-ipc 0.2.0@26ed56fa9db06e4ca6e8920c0ede2e01e219bb9c
- pocketmine/snooze 0.5.0@a86d9ee60ce44755d166d3c7ba4b8b8be8360915
- ramsey/collection 2.0.0@a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5
- ramsey/uuid 4.7.4@60a4c63ab724854332900504274f6150ff26d286
- rhumsaa/uuid unknown@unknown
- symfony/filesystem v6.2.10@fd588debf7d1bc16a2c84b4b3b71145d9946b894
- symfony/polyfill-ctype v1.27.0@5bbc823adecdae860bb64756d639ecfec17b050a
- symfony/polyfill-mbstring v1.27.0@8ad114f6b39e2c98a8b0e3bd907732c207c2b534

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfHtz20aW71fppX1rpFmSwpukZp2VIzmxduxY15InMxO6nAbQIBGBAIOHJCaV735/53QDBGnJ
sRPfqv3DTsUkGt2nz/vVTf86SIpyJet3N6qs0iIfHHvDQZ2u1ODYDqYTz/X8iTeezWauOxkOmrV+
NbHcsYt31swKbM+1Z8NBJqv6WVkW5eD410G9WWPWQD8PBytVVXJBI6eYVon54EzepPG3WVpHS8ub
z0+Xqqr/ntbVfP7wmywN8fc/VJRjSrOaz78B5tWbc/1lPhB5UYukaPIYWyZNln2TZrTneinL46Oj
o3VR1jJzVLapsPxoleYqKmVSH12n9fpmnaU36midNYs0r466bce0+qgqoyPa/qjb/chsfnSZrtaZ
oidMXdPOZtc/AQlQMmAHPkMWpYzw7YfBI0usV7Sc/q+XpZLx0RV/XMpEMWNfFDJW5YHtuofHIs2j
rInVwSGgPbI/eq1Da9dFdK1q4tB8rqfP5/fOH32V4ZMHDqq6TPPFD/7krfgjQtySzxg74gMcpFlH
pzRG3w68T8T5vqm/RllRNaX67TPT4X4CHa4POh7ek9V83k0ffVWsVc4Li/AnFdU7LFhncqPK+fyC
Px/BmP3JlDHyPoTRabFayTzWSJmHAz/4NLzevYuKHGxsorpF7eHV3ddHcCdOMBSfRIzfU+zI4K4l
YJB/KdcHju18kAAz1dBgnkZfqTsVNbX6aO4OhVGd2VsREXQ4lmooZFnKzQ/WW8Y36OF7qcobMjnP
9vf0N2oR2idl9FWcVmsJEv4cVozLpIeLXnqkVx7YvrVvUhrZ7f6tbvx5NKY9NHJV3xbl9dEqWquj
JeBnQOo8/1au1IWkHZ7rsYOpPd1DcHfX0VfRUtatLdvWW3G0u+vM7Hqj8rgoj7aQjkIVl3garcui
LqIi69vFa/VzAygalwN/X24G/fmc8J/PDQHz+T0UjL7Sb3cB38fOPaAtWp3a7uD0yLZmrjPRTt96
iLPf6YdLxGXEfPjPyYcJ+fCeLSkfgfyHOPKItM6zNOr2R6LuTu0Po747v0X1TNbSCPEzcbzTb9d5
K16Ot9o2Hp+M8ee72h63f840jc5DNJbyGvHl6LW8fpGG53mtygRJANzY5I/Q+iyPiljFrS1M7bfi
Eki8Gj8f4WN4mIzr8fhu/C+DnBrP6OMdP7z4MZ6Or//7/xT63df0V0N/PaWXZoU31vS4D5qUJmiU
rjWxmrCr4k2lSh2iX+oM8bWKVEo+EWrwQUo1wPl8j0UIibmWioF0kOa1sLa+B34ACH97+F9Lxvzx
+Oy78bmmYgge6M+CSBqPXo/HMT7G3m/jXzG+GAdPz54Rf969OBgT6yBQTNW0e58oSygNKGzJqNi5
zudgUEvTB7jzCfb2AJ8e2VNv5hov4T8otiovil+UjlWZUmtVtu7Xdv6ogD5izTYV0wj2Y+YV6o8r
pMTXEOceTv5+RNDoI3TtzAMKcO/g6HdFnSZpJGvYSmW2mvwBXkxme/s+jOMH957ekxoEE+8jiaro
+U1ep9lBgpy8Fl355o8t2wv0HrN79rCCh2J9nUbXFxrhotRYOv2YcsFrXmLNget6DwC5Jxn86FT9
kXtvOtiASqRtL2WavygWC8wLtu4XaftHlXrdCs//yBVt2qwZYT/ACH/fSWvjNuwzPv/AprBVIo6k
pep75k8pVre7jl5ebFP47TDGDgdvfxsO1P+iwvxzlscgTQN6l+Y3RXajViqvAT0GV6N60L4l+tp9
MEjhkJhhY/y//ltX7Q6+48OlxSrKpJFKVL8jllXiibAP/4YJnp7n4yNHAoNcOFLiczKNNgn0JhN8
RCyXLe1C3dXwTZXgh18xa6onz/Ah8IeNTZy/fPrts3dX/7p49u7i6dVzoG8RYNt6aNab1y+IRp5k
a4i2YyYf/fWv4uRGlsZgxF+P6K1r3q7L9EbWSjwGTKBWA8x8MB8wJMMt29+fm8lQZahnMPmHtzzV
0GxPtpsOfvvS/vjS/vjS/vjS/vjS/vjS/vjS/vjS/vjS/vjS/vjS/vjS/vjS/vjS/vjY9kfbBKio
5P9aJzfPIJNitaERquJRcu69GA66+xADB57Oxohs6mVRVlSMRkWRxcVCxeqGNpDrlEahaWOLnlUu
w0zFg2OIXQ0HMTQVJTum4F1VJPVZf2AluUHRAzmf72Kz/0z9D+gHFl28urz6/tXrF2cYulVhldZE
y7Ku1xW4uEjrZROOkU0ftdDXq6M9WKixv1Y1/NPLplY7DOkG+8wAK8beLjOqBobI0lGl67qfiyF7
YIkJLUb973+AGXuQj3rAiBtNmsH2rsCxqs+P/vCueoDIUahquackp7+oaHnx8kzd0IJ/pHfp9XPC
LZZxEctqU8rPpju003oF1YFbCDWiNSEKRu2i/ams6tFwtAMKjNq21LZc6rfZtiwCaWNnhzmfifCP
KKv/ANG13GRFSdzsyLxcFut9MnmsT6Y/dseTz0fmwJjo04vzwXDfQW15sGp+BikomgmnCjjN5zp6
/B7lRBwEu6/o3dCe2U+A/45+bx2tuFJy9bmUud1/Pu9hYgi5vHr6+urNxe8JcIvZUQcDxFJ3hpi5
pbUd+R13/1PxU6Em9KdHpMdEDv8csVvIuo8EZLovHyO/5w0Ksu8uTns0dUP7FujuEvW1Uk///bmE
xsDm83bvT1HB8/zmUvUjjxnYlYm7L5OvMwj5eVGmvyC9+mxk9IFSlU6YfAoxL19dnV0umyTJ+hT1
R3etyts3qudfn5/JVSrzz0VSBxAJ4xYNnT1+2LCYniar0++LMov75GwH9w1HB0LndwPh6b/5juam
qavmOsX3a5ml6XX1/yUirgjfW8IXZPdx/zPRsAcIfPqHzNNq+Q+nx6VuqM8j771IOKh+LsvssyVN
BGw+b/fefvt95aWzNFkCd+RCjNj4ngyb8aITKKKHo8ZpUdL6KXnNGWc39c4zStq7VdYfobZ9Ve0M
raNdINXPiOnK7Q/9AkD9Z24rxypsFuzebDakMFrJetmfFskMTALi/bFlk19zEeXwWnfs02i5WdeF
GSB+ReawdLuuKXewjosVqb1lubbtzMzZZponRX8SxsDQnZF63X9cxDtPq52XS1ntkFPVkqjZWfJT
xaq15bi6UVkcGkosLYNYJZmWDBSQfekq1HVXf+kKZZeJFzbzYLWBKHLaznwT3dzLixe7IszrHe6k
izDNZYkia+DSll4LLu3Pujh7tQMlLt7xpP1BrRE7K5e7Uq1YWaudhavVWhfYGA2M6a2LKr3rzyoV
BEv6vGg0Z1tteg2eofZOd9lbLVfFjoz0IcU/X+6woy6uVZ7+siv5PUPAI+H23pzbMt1Tmbs7owgk
PEJtIxmUg0cK67+ka52kzViV/w2VF68uIomccAsGBv5TWr9b8el33mQZeLFcG30l1VO5KmXWc2E7
9k/mJSv1rp/vaiXhimNw7NiBC7FX76gqPk5kVsFrtc3jwbE/nWGPlI7nJ1Hs2pMwcWdTadmTZBIF
M0t6Ez/yZTAJfCsKbMt1iLLGoPIizZs7sXaU8ClojmzfGTHCaSQe2cFs9CZs8roRly8vxFWjxP80
uQiE4xw77rE1E2+uToVjOa64mwbvAlJFOvbvuxfFWu51qrNcvyuqdmPyWvSQmQcEA6iRKt/BskpZ
popdoYyXILVUR2SRIzrE0rcRbFL/k8C3gUAyS5TvqJlKpGPPplEok0B5Uzu2Z8FUOe6ECogQVF0f
GVcGbYQ6nlgynjqRsoNpNHVC6VqxHVm2iqaBbQcy9J0EDPYmU3bBkBH8BNX9MstCGV2PbhBf4Zrp
Fgh4ep0Xt/mJ+SSXtCiLqlJHoFpWOZ3/3zhjBKITz7ECS8We73qAPUvCWeLYoMGeBl4SeZNwplzf
moSAkau6VJWSZbRkBqzkeq3u3+6e06aQMq9Rs16UMIhRBcVdSaPg1slkFoaujH3PUYk9U1NnmsSJ
nchAxpHv0TcvdMPQvx80yJYmh7T+sx2ETBBmT0I3jt3EC6fKDYOJP4v8eOrFKgBf/TB0rDAAv105
ux8yzHT1Ps42bXQS2kEEeIlU1nTquuCYFUOCyXQaq0lkJ54bRsEkegDy1mwGDjcY9hGPVJI4sJ4w
9mPHmybuBLKZhMpVUzeIfTdQ7sR3ArUHnj0yhz7jTLwTX0YTpeTMlkkIHYsjbzZN/Ei5XqQCZzaJ
fbBDzuQupHsVy6Yq4ySApky8YDYJgjCScqL86dR3ILupHzlu5PhqGvm+dPYAFhnDoJhln0jLg57Z
sBMrJG8wcy0LBDqxP3MdsHMyTQLpK3sXBl9zMmdsDAo+/ySWyrE9AHS9aTizbagPdChMbMdPEhuY
TGdRNGXD6YGCOiJz2OoOedaTCXjkJ7MwdtzQUx6xa+ZYMRiYeAnkDMu2/GQS74PSKQrc1okKopnt
RFYys3w/gtk7ro11kRPbUPJZkHiWFwHVXQidJ/DAXm8iHc+NXSinZUdTazaLA9/FRzCZQWb2dGrb
tu/tKVYe1oa53kkABBwv8KB/1jTEN+ijsqUjEwsEWrPYt21PxXsS79n3aMe+bzzo0Ww2O0kmljW1
glhFEz9QUHZfTpEdxZEz8y0EutnUCfyZH+zC3X4dce7DUeXkE0LEewdt2mkCDjmOSejFdjzx7SCO
YBSO49se3Fng+UDI8x0YeSTvg0LHdW3EPYElxX6QyFkcWvDXkQwUiT6Cb1SOgh+GToXhLNoFpA8r
GAg5UzkN4plSgRUpeFPfj+0giN1oEsJ9TfEfma41s8mNIQ+v1IaMYpuBsB84wVxvOgm8MAlDmD18
IOiTKrSlC4/lw2IQ9j3ZA9I0qQ5tE5I9mBgFrgwn8Bq+57rOzLJ8WNvESwLbt+BVgtiZkozKZbOq
pGzXv+/Gq80qKfLNEaW91aaCMyRtCCjaWSdJ7JOrC2EOdhghRDnRFKjDT0+gXX48m3lBiIjVg7Mu
sg1gZaM2876BJkxAMwhD0EMEUBGseRpYYQgn4wdx4ILcREXQFBAh74PVS3NbcFMZA4UkCLHaiaBg
09CC/49n1mTiOpFjTSInRMTTNVEnzvGGc65HgkpnukGXpIum5DMsQSwQSVGKnZRpnj8SV0sYjahU
XQOJSshSiXqpRJGrCl9kLSKZ0/3IULVX1mJ8EfrUZIw4ACOrkWAQrMtihZUJAdiHWclEDUWBN2VF
IEWI1PJabIqmNLBEmgjkfmmS8g5IVOiOZLYhwN+p2w7cEUoFieK2ErdF/pdakJnLUqBiLeCHUnL8
G8KwXqaVpvt2qXKhwyAAjOf5PG+BHc9zIR59v1SEmKgL7ILUFCDM6RN4gEylotIk1q8ZVe19BfiZ
qZr5hZwyjZTQzp1GVgQZHI/UKJOUui/UseCkk15Uy6aOoaUjc8P1WMwH+kRO0OmqiucDxuxplhW3
Iksrwra9GCZuUin+b6PKDc35mb6MzKtjQcU4L33G5blZI4CXoNxPQGJgCkELN8Kwkubran7Uve4h
++h7KCo0AnyVcSzgZTX7ia10BilWStKBMKWTAkwPFSEN5qifG5kR2xbpDeYiFCPzPTCbIt89JOh6
RzUqFR2qjcB2OjI8xmve+7tmFYIr0Kqn1SaPrmR1LehUGno05glvwC1W7ZZSmrYsi7xoID1Mr4aC
mytCFxBkD0NBGXKpL2Iwb25VSGOrJjfHvhr4JYsXNEHLyuIuhYYpsAEksebmHXLEW4PQeUK6SnNI
J4cirf8C9tUlL4tVTcelpDJ7i8UBaGhgNw6zhckYGUqPGdS+rkpWjrLJcxJnTGV1sWYhcMVTjcWZ
ujHfxSpdLGHMJeq0Yd/4jOIQR8qyWdd6VDOMGIOSWxm6WLgwSi4cYm0Q8qZIY6B9PwakI6RzSN5T
aNe4p2iYPNKTOk2b5yuF7TbaKL/NihDaQ50kocdhB6u0JtteqYUMNzU4Li41qy1mbloRbF5+RVK7
TZnzrFEw2tuRBtQqWcUUJilQhEcC9jnDSkql2i21kkNaDZmpWBQQVEFmSlpBGy0YzRGjdiwsogK7
swvWpf3/egqoNfch/JeyjP8c/lVdrBkF4z47lAy4SsB9oLIjv9ciRLu2WKEw9Qxi7AS+Z6sw+FV/
+QwYsl0wSuQxRNQg+OQIPkJfMiXtLjTK2iIpWHWz1V2kVFxtKdKO69XVs2Nx9fz8Urw4f3l+JZ5e
XLw4f3YpLp69Ft+/ev33Z6+HApPE1SvMeia+f/7qxTNx8frV6bPLy/G+C9jhh+MHhh0XqkwLDsjk
iCsiEGUeu2TmRudsbfAeKUHMvoWnjOAKlXazDOq0yEEnHDS0ieh9SNm0kt0uKbKCJ+SC9DSGrIHA
9W4duY5IvMcriiEU53nB+P3ZpAumrwyxrVVE6YDmLKGr5arXdjRAvdS62pLqWobW6vB+lAzlrqF8
IcsQljHaJrPsgO7nLpsaoWNWCbMKvnsl84aTjz4mSMwa6ODhsI0J+0rYqqEOrwmSxVrTu9qa4Fi8
0j5fKzyyh6LJ4g6XFEHkNhdb/CsNeM3og9DAsgyt2O0bdhbvBUlWHQ2hoy0pi1UbbPVqM2PUV82+
hIkaI8n3dEPco1I72nHZJowkshI7kRoaRY6b1VpnVzqFE+bFiF608jqjSWYB485othTgCWEexi7v
YTCCNgIfdriBklVVo8gx1EtIbdFmm+S0aLctVsNWkDpHMEnlWGNDUx/k00rejbjNX7W4n8o1jaar
ZoUYi/BaEvBa5sgqIUih709rLLZ8JXsxrGSLeV/HkGyvDUa84Yiy4AZB1+skdlboV/s6TbkReT0N
X09uTUjDMhP7lHHmMOLWbkfbGVDhXAXpI3EP2OkEQ0NZ85VQoddoCrfUYZnhp6an3Zkmb7NdYmBG
ZYCB+2FQH9LDeW6uPR6bEIHUbFlkOsUM6Wo9Z+KMMrImqJAJMuzbdOVj3urQEqou2dTh7VFfSu0r
cqvlpibgQzGyewJk4fHGo7pFxoQA9trbPJYPViiFjDXlVMtwok+LMWjQGovnyAWhS084uROnF2+G
WAscQtjXbRpD7TlX0N6zgz9i+MciaNPubUZeMXf6OXXccBDp7GwhVxT++SWsLY9gdngUVFnlESwp
bJAkyQ10P26iHeMUdDC4jYe9Xfo1yq6gtOH3pr4nqVZGmSwX7FqlKRnfF9qOt8zYl8HVKJIRr+Z0
akmY9quU4ftIQAmpYoV2gcXIUihxWNeMsAZkkLqX2L70bYs9OlV5d+TlKeWW2ViQUN5c5Bdt8bEt
iKm2oo1ukUbQwmadr0fmea/ae2m8UJX+ojquEWktyypKAEwKiTJGm0sv1fBmjl50OBYXv8Nm3jEp
5YJIAKvBimqdcQZH5fYKyJPzkyXp7WmWYpbuH5T6kr94efWGMa1AEpFNekT9Clbt7Xa62Bq3vndV
NyNadczY9utlaCMdtLLvS8TL9mJnR2aNpySNxoKj9lJSUiTSFXhTk7OENPgfrILb1joN8d0w0kvi
BKIQByakLJLDmzEJnVphbm1slihRul9iXL+pLs9ecdJ4dn759Gvki5xfNjmbLwWwhiIHn8LqpCkl
4zQ/Po379deWzq3v4+Pq47aI/UrYVLyaFH4J983vhWlZVLrJovi3moVOZoyHsAmYxlpDO10WRcWN
mLZ2VW13gqMatbFFJW/a6ImvaqTfcYu719YAYnzfQCexpkf1U5HmukHCnPqL+GdY3JEnLMX5mTj4
55vzs0PIHW4QOGD+LcRGgknZoLmmLWPDH52OwRqKrexymN8/v37Rwjf1bm/kL7wZ/+KW20QkXpOa
MW1F2zEzacUd8BvRJYsnRZLwtniXJpvRXZPGW4EwP0e7zaor7jZpU9P/NprmAUc+Y1dNZbpe5GZr
HXbMmpFecyzMMTxto0OqCRdmF8oJZL7oaraclmX7qcmwnXWTqttRl7Dc1yDUzH26KhryHomO/caZ
gGUtaynXoWybW0MQP33nZAWLX3Pq0lvMhOdKtyJCpYGFKiHbr9byNm9jkPn1GakWDe8mQZp82qgj
/72dZEm/Dxey1Vjs12JJnx1Ad69pxeeGZCpVGith9qCOqITOVE3YJ2RBeQFmqFhnA/zQRWvunhn5
yihSmeLiR2so75ql19iCSn92JpkEMxZlcVsvtSvCFlIsNbSen4IBV7XOMhjZEbG9RW20lYEm7fys
6tFFnpaEp6EJfarbkWm6aG3mps9Q+3wGvBFQROXfPaWR6r5TgbMV0LZ9d9zGqbGQ+/pknNKtTLlq
R5DQkTqkNtS6yVpzMA8UWHmOCQeuQxtyuUek804USckjIfUxhRSNmIblsUnpqL/KTQQ9rDMi83MS
ILL1vPHWmZHFjejXX3tDncHvDpvbEL1YDTsf6Xtg3cwlhHmsURnT/ZJxWjDGcGGbFRXBMNGa+slR
tUWdwo95L7bvmQR2X3KxKNXCtE5Nn1W3k2rzQ5od+hg/+JBXZ6/oVxQj4+x13Ce3dKt0pSVhvLe8
Y8WIbwngsXHvcAPxt+N8s6ZbXFo47zEVAtXvjYYhw6HLDhyjenHklM4gVL9niYQtWy8lbEWRx6Z/
TqDLvxEJElUiNx2Rv8spyOm3bUzSEUHu9EDNTZReEG1QayBnYZ/ZuiYDkKWs37d7vCdVTVdfrHW6
2kYGE2UJKM0nradAQFIk90wbcnPXLGob+ePtBuZNf4eWc+81nyPOXc1PofWZRC8b4IraGH4Mzua6
thF0cha3vTQzt0u50wWiTBuGkcsmDZ8ekO0RssA9okw0F5Rsc8rTBVXuM/dhUs5HXlTXQwdqvBgz
kXjQi4bijLQLn6qOxoe91CjN103dV5WHshcTGrX+arvvdQpbTOq0NlrU9gSXZlB7+7Kjv+WXIGMr
NYVp0gGiKwhNqc/TyPG2jTIdhADPOOo2e0CGSTWWFp1OaypT1nM5rjNGkmUMEZUoiG/4TAvf5LqV
rDBQNAGPngpSdCDDw5yJU4FB54W0lLNunbV2mkHnGgbIYQtFP1JOAtuOBUuPuUBlRUmhEhqzj4Iw
//JJTEdX7VnY/pkmjK1SWTI2PSVKZAxlMteAdCsuZfv44S1KXwqbyPYOwFOlIzGZe3qntjvznHnv
sPWYetrzgUaaGNaesUlUeHrnUJmd40MtAlpyjC1b1E5bDrUCNdOHuhmo08eW/eJfkBWxG66Zt0yM
HXZc0i4opdDTYMZBS8Sh3o2S0yGnC6RTJDOa2hJIKBDv6W4fapAxKynDoXVkTU2lu5tVsVLalt9n
ikGFloA3Ral3nptfuNHw7hStDjKkOCp+2OPu254I6dxxKz86DzUmpv+Vg+pQyy2tWRuNylPNglnG
DWMD8+2tfguvYiTC5QbWDcX+vlQ5XZPq7Oi0zuFR0Tbk54EQudnH3LShUwxGDbkLkGznDMVjhx2x
PgWh7jS5HY0nnY7KGHQDlWINQG+xufixGwbZ6u5HMfpK/IjX/MDrrqEIhH2TRrAYIC83EMc59eh0
RkwTAG4+0AD5cQvLrPtR/Ce+37uU5s4HP3ZI6vQOW9IDEfzYaXelo3/yAVQQ/9RUpMv8a2hKmR87
/9GisIXCwOHxkMDlsUaIoe4Od6h9CL6Z/R+Maie6lSTBtTKi7jxfA9uIA9g6a0tPg5CypFllTnU2
nUEif7sBi+JDI+LHMCAKJI8fozR+/NjR8qOd+vJrBdiN3yPAYe/1j1qf8qKH7hPBl8V69BjNQh2y
gO5Rqr3gyxY9NVxTki9G4mC5WSPNOhT8E0KmM0XZdqfRrddsRkC2JmUbaWTNKDUWxcSiD40w5uwM
6SyOD+uqHr52ezZkmphma+1lCQEA+rHldo8qUz7S4eWdueWw4/X1GTSJEqDioud9kB+plqCtFbDx
6lK4K5f7d1F2gwwf5OiygvI9Vd9buQqNDUdM6kXyAQD9vGKdKVN2m16cpJvWel8e118BkRJUz9JV
7HbHY/HNi6dXepDafIrO9v5mblIO/dkd3FGuhu5dnJb1kOukv5neir7t0T820YIhbiP8m1NN2Zh8
MENCEW2E/p13U7YVUdsrLrt7Ipzuk4AzGfE9nKrl06i9YwJ70420R99wns9b8fwdINyJMiPveiMj
7uj0Wi2F7rax/CvTZo+uqTFZcfMUZUeYZmm90WbS6QlQqSEV/SP9sW4/EZUMfwQku0KJ7l3tC5Vu
Sl1sRXzK16X4vtAcVgfMGr6j7TjCto9d+9i3u0vaNKG90/NEofbB86qo4ycXzjPxd+ipvslDw3rb
EUW7h99S3vjEntmoPXcHbwIe5g2pgU5X459UTXmT3siMd5V3pk1WPQlmNLLTh3liBzR2u0xrNaKg
+aTIacDkuXxzaHcoXWNPPaLvLnXbFklCo3QMTddV2uf1zdrMj1Pqi8IsNk+Yjk7Lu3L2CTOOW1rM
EP2Tp3Lb5lJxbwpVCk/Onn3z9M2LKxrlyo8itdmv10Lj58Fv/w9JQsJ2
===END CRASH DUMP===

**Comment by 0xliam627** [comment]
Download new build [here ](https://github.com/Taylor-pm-pl/ChestKits/releases/download/v0.0.2/ChestKits.phar)
